# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: plinga 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "plinga"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["engraveness@gmail.com"]
  s.date = "2020-10-07"
  s.description = ""
  s.email = "engraveness@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/plinga.rb",
    "lib/plinga/config.rb",
    "lib/plinga/engine.rb",
    "lib/plinga/middleware.rb",
    "lib/plinga/rails/controller.rb",
    "lib/plinga/rails/controller/redirects.rb",
    "lib/plinga/rails/controller/url_rewriting.rb",
    "lib/plinga/rails/helpers.rb",
    "lib/plinga/rails/helpers/javascript_helper.rb",
    "lib/plinga/rails/helpers/url_helper.rb",
    "lib/plinga/user.rb",
    "plinga.gemspec"
  ]
  s.homepage = "http://github.com/engraveness/plinga"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Integration with the game distribution portal"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

